config/routes.rb
Rails.application.routes.draw do
  root 'materials#index'
  resources :materials
  post "materials/:id/"    => "materials#show"
  put "materials/:id/edit" => "materials#edit"
  get "mymaterials" => "materials#mymaterials"
  get "boughtmaterials" => "materials#boughtmaterials"
  get "messages" => "materials#messages"
  post "messages" => "materials#messages"
  delete "messages/delete/:id" => "materials#deleteMessage", as: "delete_message"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/material.rb
class Material < ApplicationRecord

	has_attached_file :data
	validates_attachment :data, content_type: { content_type: ["application/pdf", "video/mp4", "video/avi"] }

	def self.search(search)
		where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
		#where("description LIKE ?", "%#{search}%")
	end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def new
    if user_signed_in?
  	 @material = Material.new
    else
      redirect_to new_user_session_path
    end
  end

  def deleteMessage
    if request.delete? and not params[:id].blank?
      Message.find(params[:id]).destroy
      flash[:success] = "Message has been deleted!"
      redirect_to messages_path
    end
  end

  def messages
    if user_signed_in?
      Message.where(notified: 0, user_receive: current_user.id).update_all(notified: 1)

      @message_texts = Message.where(:user_receive => current_user.id).order({ created_at: :desc }).paginate(:page => params[:page], :per_page => 5)

      @message_user_ids = Message.where(:user_receive => current_user.id).order({ created_at: :desc }).paginate(:page => params[:page], :per_page => 5)
      @message_users = Array.new
      @message_user_ids.each do |message_user|
        @message_users.push(User.find(message_user.user_sent))
      end 
      #@message_users.paginate(:page => params[:page], :per_page => 5)

      if request.post? and params.include?(:message_user)
        unless params[:message_text].blank?
          @message = Message.new
          @message.user_sent = current_user.id
          @message.user_receive = params[:user_receive_id]
          @message.text = params[:message_text]
          @message.notified = 0
          @message.save

          flash[:success] = "Message has been sent!"
        else
          flash[:error] = "Message can't be empty!"
        end
        redirect_to messages_path
      end
    else
      redirect_to new_user_session_path
    end
  end

  def mymaterials
    if user_signed_in?
      @my_materials = Material.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 5)
    else
      redirect_to new_user_session_path
    end
  end

  def boughtmaterials
    if user_signed_in?
      @bought_ids = Bought.select("material_id").where(:user_id => current_user.id)
      @bought_materials = Material.where(:id => @bought_ids).paginate(:page => params[:page], :per_page => 5)
    else
      redirect_to new_user_session_path
    end
  end

  def index
  	@materials = Material.all.paginate(:page => params[:page], :per_page => 5)

    if params[:search]
      if user_signed_in?
        @materials = Material.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
      else
        redirect_to new_user_session_path
      end
    else
      @materials = Material.all.paginate(:page => params[:page], :per_page => 5)
    end
  end

  def edit
    if user_signed_in?
      @material = Material.find(params[:id])
      if @material.user_id != current_user.id
        redirect_to materials_path
      end

      if request.put?
        @material.title = params[:material][:title]
        @material.description = params[:material][:description]
        @material.price = params[:material][:price]
        unless params[:material][:data].blank?
          @material.data = params[:material][:data]
        end

        if @material.save
          flash[:success] = "Material has been updated!"
          redirect_to edit_material_path(@material.id)
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  def show
    if user_signed_in?

      @material = Material.find(params[:id])
      @material_user = User.find(@material.user_id)
      @comment = Comment.new
      @comment_texts = Comment.select(:text, :created_at).where(:material_id => @material.id).paginate(:page => params[:page], :per_page => 5)
      @comment_users_ids = Comment.select(:user_id).where(:material_id => @material.id).paginate(:page => params[:page], :per_page => 5)
      @comment_users = Array.new
      @comment_users_ids.each do |comment_user|
        @comment_users.push(User.find(comment_user.user_id))
      end 
      #@comment_users.paginate(:page => params[:page], :per_page => 5)

      if @material.user_id == current_user.id or Bought.where(:user_id => current_user.id, :material_id => @material.id).exists?
        if request.post? and params.include?(:comment_material)
          unless params[:comment_text].blank?
            @comment.text = params[:comment_text]
            @comment.user_id = current_user.id
            @comment.material_id = @material.id

            @comment.save
            flash[:success] = "Your comment has been added!"
          else
            flash[:error] = "Comment area can't be empty!"
          end
          redirect_to material_path(@material)
        end
      end

      if @material.user_id == current_user.id
        @status = 1
        @user_reputation_status = 1
        @material_reputation_status = 1
      else
        unless Bought.where(:user_id => current_user.id, :material_id => @material.id).exists? 
          if request.post? and params.include?(:buy_material)
            if @material.price < current_user.budget
              bought = Bought.new
              bought.user_id = current_user.id
              bought.material_id = @material.id
              current_user.budget = current_user.budget - @material.price
              @material_user.budget = @material_user.budget + @material.price

              @material_user.save
              bought.save
              current_user.save
              @status = 1
              flash[:success] = "Material has been bought!"
              redirect_to material_path(@material)
            else
              @status = 0
              flash[:error] = "Not enough budget :("
              redirect_to edit_user_registration_path
            end
          else
            @status = 0
          end
        else
          @status = 1
          @user_reputation_status = 2

          if request.post? and params.include?(:message_user)
            unless params[:message_text].blank?
              @message = Message.new
              @message.user_sent = current_user.id
              @message.user_receive = @material_user.id
              @message.text = params[:message_text]
              @message.notified = 0
              @message.save

              flash[:success] = "Message has been sent!"
            else
              flash[:error] = "Message can't be empty!"
            end
            redirect_to material_path(@material)
          end

          unless UserReputation.where(:user_give => current_user.id, :user_recieve => @material_user.id).exists?
            if request.post? and params.include?(:user_reputation)
              user_reputation = UserReputation.new
              user_reputation.user_give = current_user.id
              user_reputation.user_recieve = @material_user.id

              @material_user.reputation = @material_user.reputation + 10

              @material_user.save
              user_reputation.save
              flash[:success] = "Reputation has been given to " + @material_user.name + "!"
              redirect_to material_path(@material)
            end
          else
            @user_reputation_status = 1
          end

          @material_reputation_status = 2
          unless MaterialReputation.where(:user_id => current_user.id, :material_id => @material.id).exists?
            if request.post? and params.include?(:material_reputation)
              material_reputation = MaterialReputation.new
              material_reputation.user_id = current_user.id
              material_reputation.material_id = @material.id

              @material.reputation = @material.reputation + 10

              @material.save
              material_reputation.save
              flash[:success] = "Reputation has been given to " + @material.title + "!"
              redirect_to material_path(@material)
            end
          else
            @material_reputation_status = 1
          end
        end
      end
        
    else
      redirect_to new_user_session_path
    end
  end

  def create
  	@material = Material.new(permit_material)
    @material.user_id = current_user.id
  	if @material.save
  		flash[:success] = "Material is created!"
  		redirect_to material_path(@material)
  	else
  		flash[:error] = @material.errors.full_messages
  		redirect_to new_material_path
  	end
  end

  private
  	def permit_material
  		params.require(:material).permit(:data, :title, :price, :description, :user_id)
  	end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/boughtmaterials.html.erb
<div class="container" style="margin-top:50px;">

	<% if @bought_materials.present? %>
		<div class="panel panel-info">

			<div class="panel-heading">
				<h3>Bought Materials</h3>
			</div>

			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
						<th class="text-center">Title</th>
						<th class="text-center">Price</th>
						<th class="text-center">Download</th>
						<th class="text-center">Link</th>
						</tr>
					</thead>
					<tbody>
						<% @bought_materials.each do |m| %>
							<tr>
								<td><%= m.title %></td>
								<td><%= m.price %></td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-download"></span></button>'.html_safe, m.data.url %>	
								</td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-paperclip"></span></button>'.html_safe, material_path(m.id) %>
								</td>
							</tr>
						<% end %> 
					</tbody>
				</table>
			</div>

			<div class="panel-footer">
				<%= will_paginate @bought_materials, renderer: BootstrapPagination::Rails %>
			</div>

		</div>
	<% else %>
		<h4>To buy material: <%= link_to "Materials", materials_path %></h4>
		<div class="page-header"><h3>You have no material bought by you!</h3></div>
	<% end %>

</div>

app/views/materials/edit.html.erb
<div class="page-header"><h2>Edit <%= @material.title %></h2></div>

<%= form_for(@material, url: edit_material_path(@material), html: { method: :put }) do |f| %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br />
    <%= f.text_field :price, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :data %><br />
    <div class="col-xs-offset-5"><%= f.file_field :data, autofocus: true %></div>
  </div>

  <div class="actions">
    <%= f.submit :value => "Update", :class => "btn btn-info" %>
  </div>
<% end %>

</div>

app/views/materials/index.html.erb
<div class="container">

	<% if @materials.present? %>

		<div class="row">
			<div class="page-header">
				<button data-toggle="collapse" class="btn btn-primary" data-target="#search-area">
					<h4>Material Search</h4>
				</button>
			</div>

			<div id="search-area" class="collapse">
				<%= form_tag(materials_path, :method => "get", id:"search-form") do %>
				<%= text_field_tag :search, params[:search], placeholder: "Search Materials..." %>
				<%= submit_tag 'Search', :class => "btn btn-info btn-sm" %>
				<% end %>
			</div>
		</div>

		<%= render @materials %>

		<div class="panel panel-success" style="margin-top:10px;">

			<div class="panel-heading">
				<h3>Material List</h3>
			</div>

			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
						<th class="text-center">Title</th>
						<th class="text-center">Price</th>
						<th class="text-center">Link</th>
						</tr>
					</thead>
					<tbody>
						<% @materials.each do |m| %>
							<tr>
								<td><%= m.title %></td>
								<td><%= m.price %></td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-paperclip"></span></button>'.html_safe, material_path(m.id) %>
								</td>
							</tr>
						<% end %> 
					</tbody>
				</table>
			</div>

			<div class="panel-footer">
				<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
			</div>

		</div>

	<% else %>

		<% if params.include?(:search) %>
				<div class="page-header"><h3>No material for "<strong><%= params[:search] %></strong>"</h3></div>
				<h4>To make new search: <%= link_to "Materials", materials_path %></h4>
		<% end %>

		<% unless params.include?(:search) %>
			<div class="page-header"><h3>There is no material on the system!</h3></div>
			<h4>To add material: <%= link_to "New Material", new_material_path %></h4>
		<% end %>

	<% end %>

</div>

app/views/materials/messages.html.erb
<div class="panel panel-info" style="margin-top: 40px;">

	<div class="panel-heading"><h4>My Messages</h4></div>

	<div class="panel-body">

		<% @message_users.zip(@message_texts) do |u, t| %>
			<div class="panel panel-warning">
				<div class="panel-heading">
					<a data-toggle="collapse" href="#panelId<%= t.id %>">
						<h4><%= u.name %> <%= u.surname %> : <%= t.created_at.strftime("%d/%m/%y") %></h4>
					</a>
				</div>
			
				<div id="panelId<%= t.id %>" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-3 text-left">
								<div class="page-header">
									<h3>Sender</h3>
								</div>
								<strong>Name:</strong> <%= u.name %> <%= u.surname %>
								<br>
								<strong>School:</strong> <%= u.school %>
								<br>  
								<strong>Department:</strong> <%= u.department %>
								<br>
								<strong>Reputation:</strong> <%= u.reputation %>
								<br><br>
								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#messageModal<%= t.id %>">
									Send Reply
								</button>

								<div id="messageModal<%= t.id %>" class="modal fade" role="dialog">
									<div class="modal-dialog">
										<div class="modal-content">
											
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal">&times;</button>
												<h4 class="modal-title">
													Send Message to <strong><%= u.name %> <%= u.surname %></strong>
												</h4>
											</div>

											<div class="modal-body">
											<%= form_tag(messages_path, :method => "post") do %>
											 	<div class="form-group">
													<strong><h4>Write a message</h4></strong>
													<br>
													<textarea id="message_id" style="height: 150px; width:450px;" name="message_text"></textarea>
													<input type="hidden" name="user_receive_id" value="<%= u.id %>" />
								  				</div>
												<%= submit_tag "Message", name: "message_user", class:'btn btn-info' %>
											<% end %>
											</div>

											<div class="modal-footer">
										      
											</div>

										</div>
									</div>
								</div>
							</div>

							<div class="col-xs-9 text-left">
								<div class="page-header">
									<h3>Message</h3>
								</div>
								<strong>Date: </strong><%= t.created_at.strftime("%d/%m/%y") %><br>
								<strong>Message: </strong><%= t.text %>
							</div>
						</div>
					</div>
					<div class="panel-footer">
						<div class="form-group">
					      <%= button_to "Delete", delete_message_path(t.id), { class: 'btn btn-danger', data: { confirm: "Are you sure to delete message?"}, method: :delete} %>
				      	</div>
					</div>
				</div>
			</div>
		<% end %>

	</div>

	<div class="panel-footer">
	</div>

</div>

app/views/materials/mymaterials.html.erb
<div class="container" style="margin-top:50px;">

	<% if @my_materials.present? %>
		<div class="panel panel-primary">

			<div class="panel-heading">
				<h3>My Materials</h3>
			</div>

			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
						<th class="text-center">Title</th>
						<th class="text-center">Price</th>
						<th class="text-center">Download</th>
						<th class="text-center">Edit</th>
						<th class="text-center">Link</th>
						</tr>
					</thead>
					<tbody>
						<% @my_materials.each do |m| %>
							<tr>
								<td><%= m.title %></td>
								<td><%= m.price %></td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-download"></span></button>'.html_safe, m.data.url %>	
								</td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-edit"></span></button>'.html_safe, edit_material_path(m.id) %>
								</td>
								<td>
									<%= link_to  '<button type="button" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-paperclip"></span></button>'.html_safe, material_path(m.id) %>
								</td>
							</tr>
						<% end %> 
					</tbody>
				</table>
			</div>

			<div class="panel-footer">
				<%= will_paginate @my_materials, renderer: BootstrapPagination::Rails %>
				<br>
				To delete material, mail to <strong>info@notesharingplatform.com</strong>
			</div>

		</div>
	<% else %>
		<h4>To add material: <%= link_to "New Material", new_material_path %></h4>
		<div class="page-header"><h3>You have no material added by you!</h3></div>
	<% end %>

</div>

app/views/materials/new.html.erb
<div class="panel panel-success" style="margin-top:40px;">

  <div class="panel-heading">
    <h3>New Material</h3>
  </div>

  <div class="panel-body">
    <%= form_for @material, html: { multipart:true } do |f| %>

      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :price %><br />
        <%= f.text_field :price, autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :data %><br />
        <div class="col-xs-offset-5"><%= f.file_field :data, autofocus: true %></div>
      </div>

      <div class="actions">
        <%= f.submit :value => "Create", :class => "btn btn-info" %>
      </div>
    <% end %>
  </div>

  <div class="panel-footer">

  </div>

</div>

app/views/materials/show.html.erb
<div class="container" style="margin-top:70px;">

	<div class="panel panel-primary">

		<div class="panel-heading">
			<h3><%= @material.title %></h3>
		</div>

		<div class="panel-body">

			<div class="col-xs-3 text-left">
				<div class="page-header">
					<h3>Owner Info</h3>
				</div>
				<strong>Name:</strong> <%= @material_user.name %> <%= @material_user.surname %>
				<br>
				<strong>School:</strong> <%= @material_user.school %>
				<br>  
				<strong>Department:</strong> <%= @material_user.department %>
				<br>
				<strong>Price:</strong> <%= @material.price %>
				<br>
				<strong>Reputation:</strong> <%= @material_user.reputation %>
				<br><br>
				<% if @user_reputation_status == 2 %>
					<%= form_tag(material_path, :method => "post") do %>
						<%= submit_tag "Give Reputation", name: "user_reputation", class:'btn btn-warning' %>
					<% end %>
				<% end %>
				<br><br>
				<% if @status == 1 and current_user.id != @material_user.id %>
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#messageModal">
						Send Message
					</button>

					<div id="messageModal" class="modal fade" role="dialog">
						<div class="modal-dialog">
							<div class="modal-content">
								
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h4 class="modal-title">
										Send Message to <strong><%= @material_user.name %> <%= @material_user.surname %></strong>
									</h4>
								</div>

								<div class="modal-body">
								<%= form_tag(material_path, :method => "post") do %>
								 	<div class="form-group">
										<strong><h4>Write a message</h4></strong>
										<br>
										<textarea id="message_id" style="height: 150px; width:450px;" name="message_text"></textarea>
					  				</div>
									<%= submit_tag "Message", name: "message_user", class:'btn btn-info' %>
								<% end %>
								</div>

								<div class="modal-footer">

								</div>

							</div>
						</div>
					</div>
				<% end %>

			</div>

			<div class="col-xs-9 text-left">
				<div class="page-header">
					<h3>Material Info</h3>
				</div>
				<strong>Date: </strong><%= @material.created_at.strftime("%d/%m/%y") %>
				<br>
				<strong>Description: </strong><%= @material.description %>
				<br>
				<strong>Reputation: </strong><%= @material.reputation %>
				<br><br>

				<% if @material_reputation_status == 2 %>
					<%= form_tag(material_path, :method => "post") do %>
						<%= submit_tag "Give Reputation", name: "material_reputation", class:'btn btn-warning' %>
					<% end %>
				<% end %>
			</div>

			<div class="row">
				
			</div>

		</div>

		<div class="panel-footer">
			<% if @status == 0 %>
				<%= form_tag(material_path, :method => "post") do %>
					<%= submit_tag "Buy", name: "buy_material", class:'btn btn-info' %>
				<% end %>
			<% else %>
			 	<%= form_tag(material_path, :method => "post") do %>
					<%= link_to  "Download", @material.data.url %>
				<% end %>
			<% end %>
			
		</div>
	</div>

	<div class="panel panel-info">

		<div class="panel-heading"><h4>Comment Area</h4></div>

		<div class="panel-body">
			<% unless @status == 0 %>
				<%= form_tag(material_path, :method => "post") do %>
				 	<div class="form-group">
						<strong><h4>Write a comment</h4></strong>
						<br>
						<textarea id="comment_id" style="height: 150px; width:450px;" name="comment_text"></textarea>
	  				</div>
					<%= submit_tag "Comment", name: "comment_material", class:'btn btn-warning' %>
				<% end %>
			<% end %>

			<% @comment_users.zip(@comment_texts) do |u, t| %>
				<div class="row">
					<div class="col-xs-3 text-left">
						<div class="page-header">
							<h3>User</h3>
						</div>
						<strong>Name:</strong> <%= u.name %> <%= u.surname %>
						<br>
						<strong>School:</strong> <%= u.school %>
						<br>  
						<strong>Department:</strong> <%= u.department %>
						<br>
						<strong>Reputation:</strong> <%= u.reputation %>
					</div>

					<div class="col-xs-9 text-left">
						<div class="page-header">
							<h3>Comment</h3>
						</div>
						<strong>Date: </strong><%= t.created_at.strftime("%d/%m/%y") %><br>
						<strong>Comment: </strong><%= t.text %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="panel-footer">
		</div>

	</div>
	

</div>