config/routes.rb
Rails.application.routes.draw do
  root 'materials#index'
  resources :materials
  post "materials/:id/"    => "materials#show"
  put "materials/:id/edit" => "materials#edit"
  get "mymaterials" => "materials#mymaterials"
  get "boughtmaterials" => "materials#boughtmaterials"
  get "messages" => "materials#messages"
  post "messages" => "materials#messages"
  delete "messages/delete/:id" => "materials#deleteMessage", as: "delete_message"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>NoteSharing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "NoteSharing", root_url, {:class => "navbar-brand", :style => "font-family:Pacifico;"} %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%- if current_user %>
              <li>
                <%= link_to '<span class="glyphicon glyphicon-edit"></span>&nbsp; Profile'.html_safe, edit_user_registration_path %>
              </li>
              <li>
                 <%= link_to '<span class="glyphicon glyphicon-list"></span>&nbsp; My Materials'.html_safe, mymaterials_path %>
              </li>
              <li>
                <%= link_to '<span class="glyphicon glyphicon-list-alt"></span>&nbsp; Bought Materials'.html_safe, boughtmaterials_path %>
              </li>
              <li>
                <%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp; New Material'.html_safe, new_material_path %>
              </li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <%- if current_user %>
              <li>
                <% if @messages_count == 0 %>
                  <%= link_to '<span class="glyphicon glyphicon-send"></span>&nbsp; My Messages'.html_safe, messages_path %>
                <% else %>
                  <%= link_to '<span style="color:red;" class="glyphicon glyphicon-send"></span>&nbsp;<font color="red"><strong>My Messages</strong></font>'.html_safe, messages_path %>
                <% end %>
              </li>
              <li>
                  <%= link_to '<span class="glyphicon glyphicon-log-out"></span>&nbsp; Log Out'.html_safe, destroy_user_session_path, data: { confirm: "Are you sure?" }, method: :delete%>
              </li>
            <% else %>
              <li>
                  <%= link_to '<span class="glyphicon glyphicon-log-in"></span>&nbsp; Log In'.html_safe, new_user_session_path %>
              </li>
              <li>
                  <%= link_to '<span class="glyphicon glyphicon-user"></span>&nbsp; Register'.html_safe, new_user_registration_path %>
              </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="margin-top: 50px;">
        <div class="row">
            <div class="col-xs-offset-4 col-xs-4 text-center" >
                <% flash.each do |a, b| %>
                    <% if a == "success" %>
                      <div class="alert alert-success" style="margin-top: 30px;">
                    <% else %>
                      <div class="alert alert-danger" style="margin-top: 30px;">
                    <% end %>
                      <button class="close" data-dismiss="alert">&times;</button>
                      <%= b %>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="row text-center">
         <%= yield %>
        </div>
    </div>  

  </body>
</html>